import React, { useMemo, useState } from "react";
import { ShellLayout, MetricTile, AIInsightsTile, KpiCustomizeButton } from "@/components/layout";
import { useKpiPreferences, KpiOption } from "@/hooks/useKpiPreferences";
import { CHANNEL_BAR_CLASS, CampaignChannel } from "@/styles/channelColors";
import { ChannelLegend } from "@/components/common/ChannelLegend";

type Channel = "postcard" | "email" | "sms";

interface ChannelMix {
  postcard: number;
  email: number;
  sms: number;
}

interface Campaign {
  id: string;
  name: string;
  audience: string;
  dropsLabel: string;
  lastDropDate: string;
  sent: number;
  responses: number;
  respPct: number;
  roas: number;
  revenue: number;
  channels: Channel[];
  channelMix: ChannelMix;
}

const CAMPAIGNS: Campaign[] = [
  {
    id: "spring-has-sprung",
    name: "Don's Garage: Spring Has Sprung",
    audience: "Current synthetic customers · last 9 months",
    dropsLabel: "1 drop",
    lastDropDate: "Last drop Mar 5, 2024",
    sent: 2800,
    responses: 194,
    respPct: 6.9,
    roas: 16.1,
    revenue: 22400,
    channels: ["email"],
    channelMix: { postcard: 0, email: 100, sms: 0 },
  },
  {
    id: "summer-ac-tuneup-1",
    name: "Summer A/C Tune-Up",
    audience: "Vehicles in warm-weather ZIPs · last 18 months",
    dropsLabel: "2 drops",
    lastDropDate: "Last drop May 24, 2024",
    sent: 5000,
    responses: 220,
    respPct: 6.8,
    roas: 9.9,
    revenue: 40900,
    channels: ["postcard", "email", "sms"],
    channelMix: { postcard: 40, email: 30, sms: 30 },
  },
  {
    id: "back-to-school",
    name: "Back to School",
    audience: "Minivan/SUV households · schools within 10 miles",
    dropsLabel: "1 drop",
    lastDropDate: "Last drop Aug 15, 2024",
    sent: 2600,
    responses: 162,
    respPct: 6.2,
    roas: 7.6,
    revenue: 19500,
    channels: ["postcard"],
    channelMix: { postcard: 100, email: 0, sms: 0 },
  },
  {
    id: "black-friday-synthetic",
    name: "Black Friday Synthetic Push",
    audience: "High-mileage synthetic customers · last 24 months",
    dropsLabel: "2 drops",
    lastDropDate: "Last drop Nov 27, 2024",
    sent: 5500,
    responses: 337,
    respPct: 9.1,
    roas: 10.7,
    revenue: 64800,
    channels: ["postcard", "email"],
    channelMix: { postcard: 60, email: 40, sms: 0 },
  },
];

// Map local Channel type to shared CampaignChannel
const channelToShared: Record<Channel, CampaignChannel> = {
  postcard: "postcard",
  email: "email",
  sms: "text",
};

const KPI_OPTIONS: KpiOption[] = [
  { id: "campaigns", label: "Campaigns" },
  { id: "totalSent", label: "Total sent" },
  { id: "totalResponses", label: "Total responses" },
  { id: "avgRoas", label: "Avg ROAS" },
];

const OneOffCampaignTrackerPage: React.FC = () => {
  const [tab, setTab] = useState<"overview" | "drops">("overview");

  const totalCampaigns = CAMPAIGNS.length;
  const totalSent = useMemo(() => CAMPAIGNS.reduce((sum, c) => sum + c.sent, 0), []);
  const totalResponses = useMemo(() => CAMPAIGNS.reduce((sum, c) => sum + c.responses, 0), []);
  const avgRoas = useMemo(() => CAMPAIGNS.reduce((sum, c) => sum + c.roas, 0) / CAMPAIGNS.length, []);

  const { selectedIds, setSelectedIds } = useKpiPreferences("one-off-campaign-tracker", KPI_OPTIONS);

  const renderKpiTile = (id: string) => {
    switch (id) {
      case "campaigns":
        return <MetricTile key={id} label="Campaigns" value={totalCampaigns.toString()} helpText="Number of one-off campaigns run during the selected period." />;
      case "totalSent":
        return <MetricTile key={id} label="Total sent" value={totalSent.toLocaleString()} helpText="Total messages sent across all one-off campaigns." />;
      case "totalResponses":
        return <MetricTile key={id} label="Total responses" value={totalResponses.toLocaleString()} helpText="Total customer responses generated by one-off campaigns." />;
      case "avgRoas":
        return <MetricTile key={id} label="Avg ROAS" value={`${avgRoas.toFixed(1)}x`} helpText="Average return on ad spend across all one-off campaigns." />;
      default:
        return null;
    }
  };

  return (
    <ShellLayout
      breadcrumb={[
        { label: "Home", to: "/" },
        { label: "Reports & Insights", to: "/" },
        { label: "One-Off Campaign Tracker" },
      ]}
      rightInfo={
        <>
          <span>
            Store group: <span className="font-medium">All Stores</span>
          </span>
          <span>
            Period: <span className="font-medium">Last 12 months</span>
          </span>
        </>
      }
    >
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-3">
        <div>
          <h1 className="text-xl md:text-2xl font-semibold text-slate-900">One-Off Campaign Tracker</h1>
          <p className="mt-1 text-sm text-slate-500">
            Compare one-off campaigns on response rate, ROAS, revenue and drops.
          </p>
        </div>
        <KpiCustomizeButton
          reportId="one-off-campaign-tracker"
          options={KPI_OPTIONS}
          selectedIds={selectedIds}
          onChangeSelected={setSelectedIds}
        />
      </div>

      <div className="mt-4 grid grid-cols-1 lg:grid-cols-4 gap-4 items-start">
        <div className="lg:col-span-3 space-y-4">
          {/* KPI tiles - only rendered when selected */}
          {selectedIds.length > 0 && (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{selectedIds.map((id) => renderKpiTile(id))}</div>
          )}

          {/* Main card with tabs */}
          <section className="rounded-2xl bg-white border border-slate-200 shadow-sm p-4">
            <div className="flex items-center justify-between mb-3">
              <h2 className="text-base font-semibold text-slate-900"></h2>

              <div className="inline-flex items-center rounded-full bg-slate-100 p-1 text-[11px]">
                <button
                  type="button"
                  onClick={() => setTab("overview")}
                  className={`px-3 py-1 rounded-full font-medium ${tab === "overview" ? "bg-white shadow-sm text-slate-900" : "text-slate-500 hover:text-slate-700"}`}
                >
                  Overview
                </button>
                <button
                  type="button"
                  onClick={() => setTab("drops")}
                  className={`px-3 py-1 rounded-full font-medium ${tab === "drops" ? "bg-white shadow-sm text-slate-900" : "text-slate-500 hover:text-slate-700"}`}
                >
                  Drops
                </button>
              </div>
            </div>

            {tab === "overview" ? <OverviewList /> : <DropsTable />}
          </section>

          {/* AI stacked on small screens - after main content */}
          <div className="block lg:hidden">
            <AIInsightsTile
              title="AI Insights"
              subtitle="Based on one-off campaigns"
              bullets={[
                "Summer A/C Tune-Up and Black Friday have the strongest ROAS and RESP %, ideal patterns for future offers.",
                "Back to School underperforms on RESP %; consider stronger offer or more SMS.",
                "Use Drops view to compare multi-drop campaigns and tune channel mix.",
              ]}
            />
          </div>
        </div>

        <div className="hidden lg:block lg:col-span-1 self-start">
          <AIInsightsTile
            title="AI Insights"
            subtitle="Based on one-off campaigns"
            bullets={[
              "Summer A/C Tune-Up and Black Friday have the strongest ROAS and RESP %, ideal patterns for future offers.",
              "Back to School underperforms on RESP %; consider stronger offer or more SMS.",
              "Use Drops view to compare multi-drop campaigns and tune channel mix.",
            ]}
          />
        </div>
      </div>
    </ShellLayout>
  );
};

const OverviewList: React.FC = () => {
  return (
    <div className="space-y-5">
      {CAMPAIGNS.map((c) => (
        <div key={c.id} className="border-t border-slate-100 pt-4 first:border-t-0 first:pt-0">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="text-base md:text-lg font-semibold text-slate-900">{c.name}</div>
              <div className="mt-0.5 text-[11px] text-slate-500">{c.audience}</div>
              <div className="mt-0.5 text-[11px] text-slate-500">
                {c.dropsLabel} · {c.lastDropDate}
              </div>
            </div>
            <div className="text-right text-xs md:text-sm text-slate-700 min-w-[120px]">
              <div className="font-semibold text-amber-600 text-sm md:text-base">{c.respPct.toFixed(1)}% RESP</div>
              <div className="font-semibold text-slate-900 text-sm md:text-base">{c.roas.toFixed(1)}x ROAS</div>
              <div className="mt-1 text-[11px] text-slate-500">
                {c.sent.toLocaleString()} sent · ${c.revenue.toLocaleString()} rev
              </div>
            </div>
          </div>

          <div className="mt-3">
            <div className="h-2 rounded-full bg-slate-100 overflow-hidden flex">
              {(["postcard", "email", "sms"] as const).map((ch) => {
                const share = c.channelMix[ch];
                if (!share) return null;
                return <div key={ch} className={CHANNEL_BAR_CLASS[channelToShared[ch]]} style={{ width: `${share}%` }} />;
              })}
            </div>
            <ChannelLegend
              channels={c.channels.map((ch) => channelToShared[ch])}
              className="mt-2"
            />
          </div>
          <div className="mt-4 border-b border-slate-100" />
        </div>
      ))}
    </div>
  );
};


const DropsTable: React.FC = () => {
  return (
    <div className="mt-2 overflow-x-auto">
      <table className="min-w-full text-xs">
        <thead>
          <tr className="text-left text-[11px] uppercase tracking-wide text-slate-500">
            <th className="py-2 pr-3">Campaign & drop</th>
            <th className="py-2 pr-3 text-right">Sent</th>
            <th className="py-2 pr-3 text-right">Responses</th>
            <th className="py-2 pr-3 text-right">Resp %</th>
            <th className="py-2 pr-3 text-right">ROAS</th>
            <th className="py-2 pr-3 text-right">Revenue</th>
          </tr>
        </thead>
        <tbody>
          {CAMPAIGNS.map((c) => (
            <tr key={c.id} className="border-t border-slate-100">
              <td className="py-3 pr-3 align-top">
                <div className="text-sm font-semibold text-slate-900">{c.name}</div>
                <div className="mt-0.5 text-[11px] text-slate-500">
                  {c.dropsLabel} · {c.lastDropDate}
                </div>
                <div className="mt-0.5 text-[11px] text-slate-500">
                  Channels:{" "}
                  {c.channels
                    .map((ch) => (ch === "sms" ? "Text Message" : ch[0].toUpperCase() + ch.slice(1)))
                    .join(" · ")}{" "}
                  · {c.sent.toLocaleString()} sent
                </div>
              </td>
              <td className="py-3 pr-3 text-right align-top">{c.sent.toLocaleString()}</td>
              <td className="py-3 pr-3 text-right align-top">{c.responses.toLocaleString()}</td>
              <td className="py-3 pr-3 text-right align-top text-amber-600 font-semibold">{c.respPct.toFixed(1)}%</td>
              <td className="py-3 pr-3 text-right align-top font-semibold text-slate-900">{c.roas.toFixed(1)}x</td>
              <td className="py-3 pr-3 text-right align-top">${c.revenue.toLocaleString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default OneOffCampaignTrackerPage;
